services:
  - type: web
    name: expense-tracker-api-davyd
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        placeholder: "Ex: https://seu-app.vercel.app"
      - key: SUPABASE_URL
        placeholder: "Sua URL do Supabase"
      - key: SUPABASE_SERVICE_ROLE_KEY
        placeholder: "Sua Service Role Key do Supabase"
